/* Generated By:JavaCC: Do not edit this line. XPathGrammarConstants.java */
package eu.supersede.orch.qpath;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XPathGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOUBLE_VAL = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int COMPARATOR = 7;
  /** RegularExpression Id. */
  int NAME_TOKEN = 8;
  /** RegularExpression Id. */
  int QUOTED_TEXT = 9;
  /** RegularExpression Id. */
  int ALPHA_NUMERIC_CHAR = 10;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 11;
  /** RegularExpression Id. */
  int LETTER_CHAR = 12;
  /** RegularExpression Id. */
  int CAPITAL_LETTER_CHAR = 13;
  /** RegularExpression Id. */
  int SMALL_LETTER_CHAR = 14;
  /** RegularExpression Id. */
  int DECIMAL_DIGIT_CHAR = 15;
  /** RegularExpression Id. */
  int BINARY_DIGIT_CHAR = 16;
  /** RegularExpression Id. */
  int OCTAL_DIGIT_CHAR = 17;
  /** RegularExpression Id. */
  int HEXADECIMAL_DIGIT_CHAR = 18;
  /** RegularExpression Id. */
  int UNDERSCORE_CHAR = 19;
  /** RegularExpression Id. */
  int FUNCTION = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DOUBLE_VAL>",
    "<NUMBER>",
    "<COMPARATOR>",
    "<NAME_TOKEN>",
    "<QUOTED_TEXT>",
    "<ALPHA_NUMERIC_CHAR>",
    "<ALPHA_CHAR>",
    "<LETTER_CHAR>",
    "<CAPITAL_LETTER_CHAR>",
    "<SMALL_LETTER_CHAR>",
    "<DECIMAL_DIGIT_CHAR>",
    "<BINARY_DIGIT_CHAR>",
    "<OCTAL_DIGIT_CHAR>",
    "<HEXADECIMAL_DIGIT_CHAR>",
    "\"_\"",
    "<FUNCTION>",
    "\"/\"",
    "\"::\"",
    "\"*\"",
    "\"+\"",
    "\"[\"",
    "\" or \"",
    "\"]\"",
    "\"-\"",
    "\"@\"",
  };

}
