gradle clean
cd supersede-dm-core
gradle build
cd ..
cd supersede-dm-datastore
gradle build
cd ..
cd supersede-dm-integration
gradle build
cd ..
cd supersede-dm-executor
gradle build
cd ..
cd supersede-dm-ahprp
gradle build
cd ..
cd supersede-dm-ahprp-ui
gradle build
cd ..
cd supersede-dm-garp
gradle build
cd ..
cd supersede-dm-planning-jmetal
gradle build
cd ..
cd supersede-dm-orchestrator
gradle build
cd ..
gradle build --refresh-dependencies
cd ..
